name: deploy app to positconnect

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: deploy
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://${{ secrets.CONNECT_API_KEY }}@dev-connect.fisheries.noaa.gov/
          dir: ./app/NMFS_Color_Palettes_Explorer/
          require-vanity-path: true
          access-type: logged_in
          show-logs: true
          update-env: true
