name: deploy app to positconnect

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: deploy
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://dev-connect.fisheries.noaa.gov/
          api-key: ${{ secrets.CONNECT_API_KEY }}
          dir: ./app/NMFS_Color_Palettes_Explorer/
          access-type: logged_in
          show-logs: true
          update-env: true

