name: Deploy App to Posit Connect
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.5'
      - name: Install rsconnect-python
        run: |
          python -m pip install --upgrade pip
          pip install rsconnect-python
      - name: Deploy to Posit Connect
        env:
          POSIT_CONNECT_API_KEY: ${{ secrets.TEST_CONNECT_API_KEY }}
        run: |
          set -x
          curl -v https://test-connect.fisheries.noaa.gov/  # Check server availability
          cd ./app/NMFS_Color_Palettes_Explorer/
          rsconnect deploy streamlit -v --server https://test-connect.fisheries.noaa.gov/ --api-key $POSIT_CONNECT_API_KEY ./ 

