name: deploy app to positconnect

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: deploy
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://dev-connect.fisheries.noaa.gov/connect/
          api-key: ${{secrets.CONNECT_API_KEY }}
          dir: |
            ./app/NMFS_Color_Palettes_Explorer/
          access-type: acl
