name: GHR - v2 Deploy App to Posit Connect
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: deploy
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://${{ secrets.TEST_CONNECT_API_KEY }}@test-connect.fisheries.noaa.gov
          dir: ./app/NMFS_Color_Palettes_Explorer/
          access-type: logged_in
          show-logs: true
          update-env: true
